# Do not change this version!
config-version: 2

# If true, messages will only be sent to players in radius.
# If false, everyone sees them regardless of distance.
radius-messages-enable: true

# If true, plugin checks permissions for each command usage
# If false, no permission checks are performed (besides OP for /erpc reload)
permissions-enable: false

# If true — &#RRGGBB as HEX color (1.16+)
hex-colors-enable: true

# Language: en or ru
language: en

commands:
  me:
    command-enable: true
    radius: 100
  do:
    command-enable: true
    radius: 100
  try:
    command-enable: true
    radius: 100
  roll:
    command-enable: true
    radius: 100
    # allow specifying roll [min] [max]
    extended-enable: true
    # default roll range
    default-max-number: 100
    default-min-number: 0
  todo:
    command-enable: true
    radius: 100
  whisper:
    command-enable: true
    radius: 5
  shout:
    command-enable: true
    radius: 150
