# ExeRpCommands — configuration
# Do not change this version!
config-version: 1

# Rendering
hex-colors-enable: true

# Language: en or ru
language: en

# Permissions:
permissions:
  enable: false

commands:
  me:
    enable: true
    permission: "roleplaycommands.me"
    global: false
    radius: 100
  do:
    enable: true
    permission: "roleplaycommands.do"
    global: false
    radius: 100
  try:
    enable: true
    permission: "roleplaycommands.try"
    global: false
    radius: 100
  roll:
    enable: true
    permission: "roleplaycommands.roll"
    global: false
    radius: 100
    allow-custom-range: true
    default-min-number: 0
    default-max-number: 100
  todo:
    enable: true
    permission: "roleplaycommands.todo"
    global: false
    radius: 100
  whisper:
    enable: true
    permission: "roleplaycommands.whisper"
    global: false
    radius: 5
  shout:
    enable: true
    permission: "roleplaycommands.shout"
    global: false
    radius: 150
  n:
    enable: true
    permission: "roleplaycommands.n"
    global: false
    radius: 100
  coin:
    enable: true
    permission: "roleplaycommands.coin"
    global: false
    radius: 100
  dice:
    enable: true
    permission: "roleplaycommands.dice"
    global: false
    radius: 100