name: RoleplayCommands
version: '1.2'
main: me.neyti.roleplaycommands.RoleplayCommands
author: 'Neyti'
api-version: 1.13
folia-supported: true

commands:
  me:
    description: Roleplay /me
    usage: /<command> <message>
  do:
    description: Roleplay /do
    usage: /<command> <message>
  try:
    description: Roleplay /try
    usage: /<command> <message>
  roll:
    description: Random roll
    usage: /<command> [min] [max]
  todo:
    description: RP /todo (use * to split)
    usage: /<command> <text1> * <text2>
  whisper:
    description: Whisper
    aliases: [w]
    usage: /<command> <message>
  shout:
    description: Shout
    aliases: [s]
    usage: /<command> <message>
  n:
    description: Non-RP chat
    usage: /<command> <message>
  coin:
    description: Flip a coin
    usage: /<command>
  dice:
    description: Roll a dice (d6)
    usage: /<command>
  rc:
    permission: op
    aliases: [roleplaycommands]
    description: Admin command
    usage: /<command> reload

permissions:
  roleplaycommands.me:
    description: 'Allows usage of /me'
    default: op
  roleplaycommands.do:
    description: 'Allows usage of /do'
    default: op
  roleplaycommands.try:
    description: 'Allows usage of /try'
    default: op
  roleplaycommands.roll:
    description: 'Allows usage of /roll'
    default: op
  roleplaycommands.todo:
    description: 'Allows usage of /todo'
    default: op
  roleplaycommands.whisper:
    description: 'Allows usage of /w or /whisper'
    default: op
  roleplaycommands.shout:
    description: 'Allows usage of /s or /shout'
    default: op
  roleplaycommands.coin:
    description: 'Allows usage of /coin'
    default: op
  roleplaycommands.dice:
    description: 'Allows usage of /dice'
    default: op
  roleplaycommands.n:
    description: 'Allows usage of /n'
    default: op
  roleplaycommands.reload:
    description: 'Allows usage of /rc reload'
    default: op
