name: Roleplay Commands
version: '1.2'
main: me.neyti.roleplaycommands.RoleplayCommands
author: 'Neyti'
api-version: 1.13
folia-supported: true

commands:
  me:
    description: Roleplay /me
    usage: /<command> <message>
  do:
    description: Roleplay /do
    usage: /<command> <message>
  try:
    description: Roleplay /try
    usage: /<command> <message>
  roll:
    description: Random roll
    usage: /<command> [min] [max]
  todo:
    description: RP /todo (use * to split)
    usage: /<command> <text1> * <text2>
  whisper:
    description: Whisper
    aliases: [w]
    usage: /<command> <message>
  shout:
    description: Shout
    aliases: [s]
    usage: /<command> <message>
  n:
    description: Non-RP chat
    usage: /<command> <message>
  coin:
    description: Flip a coin
    usage: /<command>
  dice:
    description: Roll a dice (d6)
    usage: /<command>
  erpc:
    description: Admin command
    usage: /<command> reload

permissions:
  exerpcommands.me:
    description: 'Allows usage of /me'
    default: true
  exerpcommands.do:
    description: 'Allows usage of /do'
    default: true
  exerpcommands.try:
    description: 'Allows usage of /try'
    default: true
  exerpcommands.roll:
    description: 'Allows usage of /roll'
    default: true
  exerpcommands.todo:
    description: 'Allows usage of /todo'
    default: true
  exerpcommands.whisper:
    description: 'Allows usage of /w or /whisper'
    default: true
  exerpcommands.shout:
    description: 'Allows usage of /s or /shout'
    default: true
  exerpcommands.reload:
    description: 'Allows usage of /erpc reload'
    default: op
